### PR TITLE
Set defaults for label, attribution, description field...

### PR DESCRIPTION
**Pull request by dnoneill**
...add in metadata field.

### CODE REVIEW

**Comment by mnyrop** [comment]
Hi @dnoneill, can you provide some context for what this pull request is doing and why?

**Comment by dnoneill** [comment]
@mnyrop It basically populates the manifest. If the @iiif_config settings are not set for 'description' and there is a 'description' field in the metadata it will add the description field to the manifest. Same with 'attribute', 'label'. It will also take all the fields except manifest, thumbnail, full, pid, order, label, and layout and add them to the manifest's metadata field. This allows for the manifests to have metadata associated with them if they are used in other websites. Here is an example using the fork in this pull request: https://dnoneill.github.io/annotate/img/derivatives/iiif/spencer-davis-7ZpvOE2psxM-unsplash/manifest.json.

**Comment by mnyrop** [comment]
Quick clarifying question: does this add new functionality that was not possible with `iiif_config` before? Or does it just pull information in without needing to configure it as before?

If it's the former, we can talk through options to incorporate new features. But if it's the latter, I'd need to float it by our maintainer group. We've really tried to make the `_config.yml` file serve as a guidebook for a given Wax site's data flows by having it explicitly describe where/how `wax_tasks` is getting its information. In other words, the `config.yml` should tell a story. While your PR makes total sense for most projects, pulling in fields implicitly/automatically seems contrary to our dev principles around transparency/control for Wax as a teaching tool.

Let me know if this does/doesn't make sense? I'll still pose it during the maintainers meeting since I'm not the sole arbiter of these things.

**Comment by dnoneill** [comment]
@mnyrop It does both. The metadata was not set before. I understand what you are saying in terms of transparency but I would also argue you are putting unnecessary burden on the user to set things like the label and attribution field especially if they have already set that information in the metadata with the same heading. It also means that the manifest, which can often be hidden depending on the use case does not get populated with important metadata and information get lost. For collections that have a link the manifest a lot of metadata gets lost if the user want to use the image in something like Mirador.

**Comment by mnyrop** [comment]
These are good points, @dnoneill. I'll share them at next week's meeting.

**Comment by pbinkley** [comment]
:+1: The ability to populate the metadata list would be a big step forward in providing rich reusable manifests. For future work, It would be nice to be able to override the default values for ```viewingHint``` and ```viewingDirection``` in the same way as ```label``` and ```description``` as well, so that multi-image items can be configured appropriately.

**Comment by mnyrop** [comment]
sorry for dropping the ball on this, all! i have outstanding questions about not cluttering the protected fields for metadata files, i.e., what if someone uses IIIF fields but doesn't mean them in a IIIF way? I think this could be handled with some thoughtful name-spacing, and any thoughts on this would be welcomed.

**Comment by pbinkley** [comment]
Perhaps something like:

```
import_fields:
  - label
  - description: summary
  - date: _date
```
Use the label field from the csv as the IIIF label; use summary in csv as description; etc. It enables the default behavior that @dnoneill wants just by listing the fields, but it also makes it explicit where the values are coming from. It also provides an easy way around the underscore on the date field, which you don't want to get into the manifest.

**Pull request closed without merging**
